# Default values for node-mylera
replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/demo-backend
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  name: ""
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/demo-app-irsa-role

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/group.name: shared-app-alb
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789012:certificate/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
  hosts:
    - host: api.demo-app.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 512Mi

env:
  - name: SECRET_NAME
    value: dev-secrets
  - name: REGION
    value: us-east-1
  - name: PORT
    value: "8080"
